name: calpal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rename: ^2.1.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^4.2.1
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: "AppIcon"
  remove_alpha_ios: true
  image_path: "assets/images/calpal_app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/calpal_app_icon.png"
  adaptive_icon_padding: true


flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/lottie/
    - assets/